//action
export const LOAD_CAFES_LOADING = 'REDUX_SAGA_LOAD_CAFES_LOADING';
export const LOAD_CAFES_SUCCESS = 'REDUX_SAGA_LOAD_CAFES_SUCCESS';
export const LOAD_CAFES_ERROR = 'REDUX_SAGA_LOAD_CAFES_ERROR';